# Generated by Django 4.1.7 on 2024-02-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userex',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userex',
            name='useraddress',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
