# Generated by Django 4.1.7 on 2024-04-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userex_name_userex_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusName', models.CharField(max_length=50)),
                ('cusEmail', models.EmailField(max_length=255)),
                ('cusPhone', models.CharField(max_length=50)),
                ('cusSubject', models.CharField(max_length=100)),
                ('cusMessage', models.CharField(max_length=300)),
            ],
        ),
    ]
