# Generated by Django 4.1.7 on 2024-04-02 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
