# Generated by Django 4.1.7 on 2024-02-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('MALE', 'Pending'), ('FEMALE', 'Confirmed'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=50),
        ),
    ]
