# Generated by Django 4.1.7 on 2024-02-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productPicture',
            field=models.ImageField(default='unknown', upload_to='productImage/'),
        ),
    ]
