# Generated by Django 4.1.7 on 2024-02-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='color',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='size',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
