# Generated by Django 4.1.7 on 2024-02-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_wishlist_color_wishlist_quantity_wishlist_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='color',
            field=models.CharField(blank=True, default='unknown', max_length=20, null=True),
        ),
    ]
