# Generated by Django 4.1.7 on 2024-02-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_wishlist_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='size',
            field=models.CharField(blank=True, default='unknown', max_length=10, null=True),
        ),
    ]
