# Generated by Django 4.1.7 on 2024-03-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_shipmentaddress_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='whole_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
