# Generated by Django 4.1.7 on 2024-03-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_whole_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='shipmentaddress',
            name='orders',
            field=models.ManyToManyField(to='order.order'),
        ),
    ]
